import type { Metadata } from 'next'

import AuthSessionProvider from '#utils/providers/AuthSessionProvider'
import ReactQueryProvider from '#utils/providers/ReactQueryProvider'

import './globals.css'

export const metadata: Metadata = {
  title: 'Create GWjun App',
  description: 'Generated by create gwjun app',
  // icons: {
  //   icon: '',
  // },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ko">
      <AuthSessionProvider>
        <ReactQueryProvider>
          <body>{children}</body>
        </ReactQueryProvider>
      </AuthSessionProvider>
    </html>
  )
}
