import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create GWjun App',
  description: 'Generated by create gwjun app',
  // icons: {
  //   icon: '',
  // },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
